spring:
  application:
    name: "oneovern"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        temp:
          use_jdbc_metadata_defaults: false

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY}
    expiration:
        access: 1h #1시간
        refresh: 14d #2주

app:
  paging:
    default-size: 10 #페이지 사이즈